language: go
go:
- 1.8
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - GOOS=linux
before_install:
- go get github.com/Masterminds/glide
install:
- "$GOPATH/bin/glide install"
- go get -t $($GOPATH/bin/glide novendor)
script:
- mv $GOPATH/bin/docker-saltCert ./
- md5sum docker-saltCert > md5.txt
- sha256sum docker-saltCert > sha256.txt
- sha512sum docker-saltCert > sha512.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: j9zmtg/OVzGjmOE8zchfe1qsXfyVpqNbGjsWSGeGvLg32+vB1T6RlSqbshh/kRZJNKIjjaF1A6v4nFDRYId+DZi1gNDHHZew5JZjijudZtvt0jmYBOW041riEfZ1eZYX8eyVjjLrXh9TNUtkpoAmSBFbHJUkaZ+xEflPk+MWmc5Lf6ksLv8NJDufxB0pl3mQaQufcaiUxYnim1z3/PMLCvs2kzwZcxd1oX/zea/tlmjXN2X8ED25kILmidgSSIZb8+hhFpIJ7AXa379QBEcHMDGw02tmMjGctr6yIb/Eth+yNgN5gQtpSkY1khfbbRM/byWxS9fpVCuZs9Qil40jnd48VWX5gxoIWOXIzzJoASGbi+F1q053EyPIj1JLJ5cSNGKNm4Nxnk/rkpQe1rGiCjxmgRcA4QQgdlgX0hCz1ZD84ZI7uOJNjivlKS3bueL4RPGTM9iX+qaZdFyg/4eTrbMWrG0r6KkUj3KCxN1kw+EgCYse+3ajTHfNrmmfEj+hd3Qfj6Kkj8Q10IfacWihtoczYDfh551LiixEfDPn6NpRr71OiWDh57SncnWRfiK68pHUvq/67/9cJSbzLUL7GIfHNb1Mu9I7XTstI1mAYkvqmQdFJ9pfqBKd3KW9eO18LXxIe769MnRQfpcp0e6tyqWVVtk55MDCdVbk5E/qb4g=
  file:
  - docker-saltCert
  - md5.txt
  - sha256.txt
  - sha512.txt
  on:
    tags: true
